### ISSUE TITLE
win10 21H2版本闪退 

### ISSUE THREAD

**Issue by wangjianhuaa** [yjmthu/Speed-Box#1]
打开软件会闪退 环境:win10 64位 21H2版本 老哥有时间看一下

**Comment by yjmthu** [comment]
好的，我新建个虚拟机试一下。请问你是最新版本的speed box吗，有没有使用过旧版本的speed box?

**Comment by yjmthu** [comment]
刚刚试了一下, 确实是闪退, 不过应该很快能修复.

**Comment by yjmthu** [comment]
bug的原因是不同槽函数的信号响应后造成了内存冲突, 这回最新版应该没问题了

**Comment by yjmthu** [comment]
非常感谢你的反映,  有问题继续联系, 没问题关闭issue哈
